name: C++ CI with Makefile and Google Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev googletest

      - name: Build project
        run: make

      - name: Run tests
        run: ./test-game
