name: ci tests

on:
  push:
    branches:
      - main
      - proj
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev googletest

      - name: Build project
        run: make

      - name: Run tests
        run: ./tests
